# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pool: ubuntu-latest
stages:
  - stage: build
    jobs:
      - job: build
        steps:
        - task: Maven@3
          displayName: 'maven app/pom.xml'
          inputs:
           mavenpomfile: 'app/pom.xml'
           
        - task: CopyFiles@2
          displayName: 'copy file to: $( build.artifactstagingdirectory)'
          inputs:
            SourceFolder: '$(system.defaultworkingdirectory)'
            Contents: '**/*.jar'
            TargetFolder: '$(build.artifactstagingdirectory)'
          condition: 'succeededorfailed'
          